brace_style = "SameLineWhere"
blank_lines_upper_bound = 1
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
fn_args_density = "Tall"
fn_single_line = false
imports_indent = "Visual"
indent_style = "Block"
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
space_around_ranges = false
struct_lit_single_line = true
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true